# Generated by Django 2.2.2 on 2024-02-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, verbose_name='nickname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
            ],
        ),
    ]
