# Generated by Django 2.2.2 on 2024-02-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_1_responses', models.TextField()),
                ('page_2_responses', models.TextField()),
                ('page_3_responses', models.TextField()),
                ('page_4_responses', models.TextField()),
                ('page_5_responses', models.TextField()),
                ('page_6_responses', models.TextField()),
                ('quiz', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.User')),
            ],
        ),
    ]
